services:
  website:
    container_name: personal-website
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3888:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
      - ~/ssl:/etc/ssl # Mount the SSL directory from the host directory direction to the container direction.
    restart: unless-stopped
      